import { AlertTriangle, ArrowRight } from "lucide-react";
import type { Asset, CriticalUnknown } from "@/domain/schema";
import type { AssetSummary } from "@/domain/coverage";
import { rankUnknowns } from "@/domain/coverage";
import { CLASSIFICATION_META, IMPACT_META } from "@/domain/labels";
import { Badge, Card, Meter, cx } from "@/components/ui";

const RECOMMENDATION_TONE: Record<Asset["recommendation"]["status"], string> = {
  expert_review: "border-amber/40 bg-amber-soft text-amber",
  investigate: "border-accent/40 bg-accent-soft text-accent-ink",
  hold: "border-slate/40 bg-slate-soft text-slate",
  reject: "border-danger/40 bg-danger-soft text-danger",
};

export function DecisionSummary({
  asset,
  summary,
  onSelectUnknown,
}: {
  asset: Asset;
  summary: AssetSummary;
  onSelectUnknown?: (unknown: CriticalUnknown) => void;
}) {
  const { recommendation } = asset;
  const topUnknowns = rankUnknowns(asset.unknowns).slice(0, 3);

  return (
    <Card className="dt-print-block overflow-hidden">
      <div className="grid gap-0 lg:grid-cols-[minmax(0,1.35fr)_minmax(0,1fr)]">
        {/* Recommendation ------------------------------------------------ */}
        <div className="border-b border-line p-4 sm:p-5 lg:border-b-0 lg:border-r">
          <p className="text-[11px] font-medium uppercase tracking-wider text-ink-subtle">
            Provisional recommendation
          </p>
          <div className="mt-2 flex flex-wrap items-center gap-2">
            <span
              className={cx(
                "inline-flex items-center gap-2 rounded-md border px-2.5 py-1 text-sm font-semibold",
                RECOMMENDATION_TONE[recommendation.status],
              )}
            >
              <AlertTriangle aria-hidden className="h-4 w-4" />
              {recommendation.label}
            </span>
            <span className="text-[11px] text-ink-subtle">
              Provisional — generated by agents, not yet adjudicated by a human
            </span>
          </div>
          <p className="mt-3 text-sm leading-relaxed text-ink-muted">{recommendation.rationale}</p>

          <div className="mt-4 rounded-md border border-line bg-surface-muted px-3 py-2.5">
            <p className="text-xs font-semibold text-ink">{recommendation.confidenceLabel}</p>
            <p className="mt-1 text-xs leading-relaxed text-ink-muted">
              {recommendation.confidenceExplanation}
            </p>
          </div>
        </div>

        {/* Coverage + unknowns ------------------------------------------- */}
        <div className="p-4 sm:p-5">
          <div className="flex items-baseline justify-between gap-3">
            <p className="text-[11px] font-medium uppercase tracking-wider text-ink-subtle">
              Evidence coverage
            </p>
            <p className="text-lg font-semibold tabular-nums text-ink">
              {summary.coveragePercent}%
            </p>
          </div>
          <Meter
            value={summary.coveragePercent}
            label={`Evidence coverage: ${summary.coveragePercent} percent`}
            tone={summary.coveragePercent >= 75 ? "accent" : "amber"}
          />
          <p className="mt-1.5 text-[11px] leading-relaxed text-ink-subtle">
            Share of {summary.claimCount} claims backed by inspectable evidence, weighted by
            classification. Not a probability of success.
          </p>

          <ul className="mt-3 grid grid-cols-2 gap-2">
            {(
              [
                ["direct_support", summary.classification.direct_support],
                ["model_inference", summary.classification.model_inference],
                ["contradiction", summary.classification.contradiction],
                ["missing_evidence", summary.classification.missing_evidence],
              ] as const
            ).map(([key, count]) => (
              <li
                key={key}
                className="flex items-center justify-between gap-2 rounded-md border border-line px-2.5 py-1.5"
              >
                <span className="truncate text-xs text-ink-muted">
                  {CLASSIFICATION_META[key].label}
                </span>
                <span className="text-sm font-semibold tabular-nums text-ink">{count}</span>
              </li>
            ))}
          </ul>

          <div className="mt-4">
            <p className="text-[11px] font-medium uppercase tracking-wider text-ink-subtle">
              Three unknowns dominating this recommendation
            </p>
            <ol className="mt-2 space-y-1.5">
              {topUnknowns.map((unknown, index) => {
                const content = (
                  <>
                    <span className="mt-0.5 shrink-0 text-[11px] font-semibold tabular-nums text-ink-subtle">
                      {index + 1}
                    </span>
                    <span className="min-w-0 flex-1 text-xs leading-relaxed text-ink-muted group-hover:text-ink">
                      {unknown.question}
                    </span>
                    <Badge className={IMPACT_META[unknown.impact].chipClass}>
                      {IMPACT_META[unknown.impact].short}
                    </Badge>
                  </>
                );
                return (
                  <li key={unknown.id}>
                    {onSelectUnknown ? (
                      <button
                        type="button"
                        onClick={() => onSelectUnknown(unknown)}
                        className="group flex w-full items-start gap-2 rounded-md border border-transparent px-2 py-1.5 text-left hover:border-line hover:bg-surface-muted"
                      >
                        {content}
                        <ArrowRight
                          aria-hidden
                          className="mt-0.5 h-3.5 w-3.5 shrink-0 text-ink-subtle opacity-0 group-hover:opacity-100"
                        />
                      </button>
                    ) : (
                      <div className="flex items-start gap-2 px-2 py-1.5">{content}</div>
                    )}
                  </li>
                );
              })}
            </ol>
          </div>
        </div>
      </div>
    </Card>
  );
}
